---
kind: Service
apiVersion: v1
metadata:
  name: vr-xcon-probe1
  labels:
    app: vr-xcon
    role: vr-xcon-probe1
spec:
  selector:
    app: vr-xcon
    role: vr-xcon-probe1
  type: ClusterIP
  ports:
    - protocol: TCP
      name: port01
      port: 10001
---
kind: Service
apiVersion: v1
metadata:
  name: vr-xcon-probe2
  labels:
    app: vr-xcon
    role: vr-xcon-probe2
spec:
  selector:
    app: vr-xcon
    role: vr-xcon-probe2
  type: ClusterIP
  ports:
    - protocol: TCP
      name: port01
      port: 10001
